In [34]:
import numpy as np
from fractions import Fraction

## Problem 11
### (a)

In [35]:
A = np.array([[3, -1],
     [4, 3]])

print("A = ",A)

Wt = np.array([[3, 4],
             [-52/25, 39/25]])

print("Wt = ", Wt)

D = np.array([[5, 0],
             [0, 65/25]])


print("D = ", D)

Di=np.linalg.inv(D)

print("Di = ", Di)

Rm=np.dot(Di, np.dot(Wt, A))

print("Rm = ", Rm)

Qm=np.dot(Wt.T, Di)

print("Qm = ", Qm)

print(np.allclose(A,np.dot(Qm, Rm)))

Qa, Ra=np.linalg.qr(A)
print("Qa = ", Qa)
print("Ra = ", Ra)

print(np.allclose(A,np.dot(Qa, Ra)))

A =  [[ 3 -1]
 [ 4  3]]
Wt =  [[ 3.    4.  ]
 [-2.08  1.56]]
D =  [[5.  0. ]
 [0.  2.6]]
Di =  [[0.2        0.        ]
 [0.         0.38461538]]
Rm =  [[5.  1.8]
 [0.  2.6]]
Qm =  [[ 0.6 -0.8]
 [ 0.8  0.6]]
True
Qa =  [[-0.6 -0.8]
 [-0.8  0.6]]
Ra =  [[-5.  -1.8]
 [ 0.   2.6]]
True


### (b)

In [40]:
A = np.array([[1, 2],
              [2, 1],
              [2, 4]])

print("A = ", A)

Wt = np.array([[1, 2, 2],
             [2/3, -5/3, 4/3]])

print("Wt = ", Wt)

D = np.array([[3, 0],
             [0, np.sqrt(5)]])


print("D = ", D)

Di=np.linalg.inv(D)

print("Di = ", Di)

Rm=np.dot(Di, np.dot(Wt, A))

print("Rm = ", Rm)

Qm=np.dot(Wt.T, Di)

print("Qm = ", Qm)

print(np.allclose(A,np.dot(Qm, Rm)))

Qa, Ra=np.linalg.qr(A)
print("Qa = ", Qa)
print("Ra = ", Ra)

print(np.allclose(A,np.dot(Qa, Ra)))

A =  [[1 2]
 [2 1]
 [2 4]]
Wt =  [[ 1.          2.          2.        ]
 [ 0.66666667 -1.66666667  1.33333333]]
D =  [[3.         0.        ]
 [0.         2.23606798]]
Di =  [[0.33333333 0.        ]
 [0.         0.4472136 ]]
Rm =  [[ 3.00000000e+00  4.00000000e+00]
 [-1.98602732e-16  2.23606798e+00]]
Qm =  [[ 0.33333333  0.2981424 ]
 [ 0.66666667 -0.74535599]
 [ 0.66666667  0.59628479]]
True
Qa =  [[-0.33333333  0.2981424 ]
 [-0.66666667 -0.74535599]
 [-0.66666667  0.59628479]]
Ra =  [[-3.         -4.        ]
 [ 0.          2.23606798]]
True


### (c)

In [41]:
A = np.array([[1, 2, 2],
              [2, -1, 1],
              [2, 0, 1]])

print("A = ", A)

# Wt = np.array([[1, 2, 2],
#              [2/3, -5/3, 4/3]])

# print("Wt = ", Wt)

# D = np.array([[3, 0],
#              [0, np.sqrt(5)]])


# print("D = ", D)

# Di=np.linalg.inv(D)

# print("Di = ", Di)

# Rm=np.dot(Di, np.dot(Wt, A))

# print("Rm = ", Rm)

# Qm=np.dot(Wt.T, Di)

# print("Qm = ", Qm)

# print(np.allclose(A,np.dot(Qm, Rm)))

Qa, Ra=np.linalg.qr(A)
print("Qa = ", Qa)
print("Ra = ", Ra)

print(np.allclose(A,np.dot(Qa, Ra)))

A =  [[ 1  2  2]
 [ 2 -1  1]
 [ 2  0  1]]
Qa =  [[-3.33333333e-01  8.94427191e-01 -2.98142397e-01]
 [-6.66666667e-01 -4.47213595e-01 -5.96284794e-01]
 [-6.66666667e-01 -5.55111512e-17  7.45355992e-01]]
Ra =  [[-3.          0.         -2.        ]
 [ 0.          2.23606798  1.34164079]
 [ 0.          0.         -0.4472136 ]]
True
