In [1]:
import numpy as np

# Problem 1

## Task (c)

In [2]:
def LDU_matrixes(M):
    L = np.tril(M, -1)
    U = np.triu(M, 1)
    D = np.diag(np.diag(M))
    
    return L, D, U

In [3]:
def Jacobi_Iter_Single(Bj, dj, x_old):
    x_new = np.dot(Bj, x_old) + dj
    return x_new

def Jacobi_Iter (L, D, U, b, x0):
    Bj = np.dot(-np.linalg.inv(D), (L+U))
    dj = np.dot(np.linalg.inv(D), b)
    x_old = x0
    
    for i in range(0, 10):
        x_new = Jacobi_Iter_Single(Bj, dj, x_old)
        print(x_new)
        print(np.linalg.norm(x_new - x_old))
        x_old = x_new

In [4]:
A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
b=np.array([1, 0, 1])
x0=np.array([0, 0, 0])

L, D, U = LDU_matrixes(A)

Jacobi_Iter(L, D, U, b, x0)


[0.5 0.  0.5]
0.7071067811865476
[0.5 0.5 0.5]
0.5
[0.75 0.5  0.75]
0.3535533905932738
[0.75 0.75 0.75]
0.25
[0.875 0.75  0.875]
0.1767766952966369
[0.875 0.875 0.875]
0.125
[0.9375 0.875  0.9375]
0.08838834764831845
[0.9375 0.9375 0.9375]
0.0625
[0.96875 0.9375  0.96875]
0.04419417382415922
[0.96875 0.96875 0.96875]
0.03125


Jacobi decay rate equals to p(A)**k

## Task(d)

In [5]:
def GS_Iter_Single(Bgs, dgs, x_old):
    x_new = np.dot(Bgs, x_old) + dgs
    return x_new

def GS_Iter (L, D, U, b, x0):
    Bgs = np.dot(-np.linalg.inv(L+D), U)
    dgs = np.dot(np.linalg.inv(L+D), b)
    x_old = x0
    norms=[]
#     xs.append(x_old)
    
    for i in range(0, 10):
        x_new = GS_Iter_Single(Bgs, dgs, x_old)
#         print(x_new)
#         xs.append(x_new)
#         print(xs[i-2])
        norms.append(np.linalg.norm(x_new - x_old))
#         print(np.linalg.norm(x_new - x_old))
        print(norms[i]/norms[i-1])
        x_old = x_new
    
    print(norms)

In [6]:
A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
b=np.array([1, 0, 1])
x0=np.array([0, 0, 0])

L, D, U = LDU_matrixes(A)

GS_Iter(L, D, U, b, x0)

1.0
0.5217491947499509
0.6428571428571429
0.5
0.5
0.5
0.5
0.5
0.5
0.5
[0.8385254915624212, 0.4375, 0.28125, 0.140625, 0.0703125, 0.03515625, 0.017578125, 0.0087890625, 0.00439453125, 0.002197265625]


## Task (e)

In [7]:
def SOR_Iter_Single(Bsor, dsor, x_old):
    x_new = np.dot(Bsor, x_old) + dsor
    return x_new

def SOR_Iter (L, D, U, b, x0, w):
    Bsor = np.dot(np.linalg.inv(w*L+D), ((1-w)*D-w*U))
    dsor = w*np.dot(np.linalg.inv(w*L+D), b)
    x_old = x0
    
    for i in range(0, 10):
        x_new = SOR_Iter_Single(Bsor, dsor, x_old)
        print(x_new)
        print(np.linalg.norm(x_new - x_old))
        x_old = x_new

In [8]:
A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
b=np.array([1, 0, 1])
x0=np.array([0, 0, 0])
w=1.1

L, D, U = LDU_matrixes(A)

SOR_Iter(L, D, U, b, x0, w)

[0.55     0.3025   0.716375]
0.9524701520913924
[0.661375   0.7275125  0.87849438]
0.4683190232433876
[0.88399437 0.89661756 0.95529022]
0.2899198344124941
[0.95474022 0.96085499 0.98294122]
0.09947863800585222
[0.98299622 0.98518009 0.99355493]
0.03876548874894403
[0.99354943 0.99438939 0.99755867]
0.014567472303895528
[0.99755922 0.9978759  0.99907588]
0.005525949257535369
[0.99907582 0.99919585 0.99965013]
0.0020909569304179846
[0.99965013 0.99969556 0.99986754]
0.000791715843896457
[0.99986754 0.99988474 0.99994985]
0.00029972156950813696


# Problem 2

## Task (c)

In [9]:
def colvec(rowvec):
    v = np.asarray(rowvec)
    return v.reshape(v.size,1)

In [10]:
def Jacobi_Alpha(x0, acc, alpha, u):
    x_old = x0
    iter = 0
    
    while True:
#         print('Iteration=', iter)
        x_new = (1/(alpha+1))*(np.dot((-colvec(u)*u+np.identity(3)), x_old) + u)
#         print('1=',(1/(alpha+1)))
#         print('2=', np.dot((colvec(u)*u+np.identity(3)), x_old))
#         print('3=', u)
#         print('4=', x_new)
#         print(np.linalg.norm(x_new - x_old))
        if (np.linalg.norm(x_new - x_old) < acc) and (iter > 0):
            print("Solution found in %s" %(iter+1), "iterations with accuracy %.3f" %acc)
            print("Solution is %s" %x_new)
            break
        iter += 1
        x_old = x_new

In [11]:
u=np.array([1, -1, 1])
x0=np.array([0, 0, 0])
alphas = [2, -4, 5, -7]
acc = 0.001

for alpha in alphas:
    print("Alpha = %.0f" %alpha)
    Jacobi_Alpha(x0, acc, alpha, u)

Alpha = 2
Solution found in 17 iterations with accuracy 0.001
Solution is [ 0.20020299 -0.20020299  0.20020299]
Alpha = -4
Solution found in 17 iterations with accuracy 0.001
Solution is [-0.99898504  0.99898504 -0.99898504]
Alpha = 5
Solution found in 7 iterations with accuracy 0.001
Solution is [ 0.12505716 -0.12505716  0.12505716]
Alpha = -7
Solution found in 7 iterations with accuracy 0.001
Solution is [-0.24988569  0.24988569 -0.24988569]


## Task (d)


In [12]:
def GS_Alpha(x0, acc, alpha):
    x_old = x0
    iter = 0
    Bgs =  -1 * np.array([[0, -(alpha+1)**2, (alpha+1)**2], 
                                       [0, -(alpha+1), (alpha+1)-(alpha+1)**2], 
                                       [0, alpha, -2*alpha-1]])
    
    dgs=np.array([[(alpha+1)**2], [(alpha+1)-(alpha+1)**2], [-2*alpha-1+(alpha+1)**2]])
    
    while True:
        
        x_new = (1/(alpha+1)**3)*(np.dot(Bgs, colvec(x_old))+dgs)
#         print(np.dot(Bgs, colvec(x_old)))
#         print(x_new)
        if (np.linalg.norm(x_new - x_old) < acc) and (iter > 0):
            print("Solution found in %s" %(iter+1), "with accuracy %.3f" %acc)
            print("Solution is %s" %x_new.T)
            break
        iter += 1
        x_old = x_new

In [13]:
x0=np.array([0, 0, 0])
alphas = [2, -4, 5, -7]
acc = 0.001

for alpha in alphas:
    print("Alpha = %.0f" %alpha)
    GS_Alpha(x0, acc, alpha)

Alpha = 2
Solution found in 5 with accuracy 0.001
Solution is [[ 0.1997895  -0.2000151   0.20006513]]
Alpha = -4
Solution found in 10 with accuracy 0.001
Solution is [[-0.99944338  0.99957274 -0.99967204]]
Alpha = 5
Solution found in 4 with accuracy 0.001
Solution is [[ 0.12498361 -0.12499756  0.12500314]]
Alpha = -7
Solution found in 5 with accuracy 0.001
Solution is [[-0.24997562  0.24998778 -0.2499939 ]]


## Task (e)

In [14]:
def SOR_Iter_Single(Bsor, dsor, x_old):
    x_new = np.dot(Bsor, x_old) + dsor
    return x_new

def SOR_Iter (L, D, U, b, x0, w):
    Bsor = np.dot(np.linalg.inv(w*L+D), ((1-w)*D-w*U))
    dsor = w*np.dot(np.linalg.inv(w*L+D), b)
    x_old = x0
    iter = 0
    
    while True:
        x_new = SOR_Iter_Single(Bsor, dsor, x_old)
#         print(x_new)
#         print(np.linalg.norm(x_new - x_old))
        if (np.linalg.norm(x_new - x_old) < acc) and (iter > 0):
            print("Solution found in %s" %(iter+1), "with accuracy %.3f" %acc)
            print("Solution is %s" %x_new.T)
            break
        iter += 1
        x_old = x_new

In [15]:
b=np.array([1, -1, 1])
x0=np.array([0, 0, 0])
ws=[0.1, 1.1]
alphas = [2, -4, 5, -7]
acc = 0.001

for w in ws:
    print("For w=%.f" %w)
    for alpha in alphas:
        print("Alpha = %.0f" %alpha)
        A = np.array([[alpha+1, -1, 1], [-1, alpha+1, -1], [1, -1, alpha+1]])

        L, D, U = LDU_matrixes(A)

        SOR_Iter(L, D, U, b, x0, w)

For w=0
Alpha = 2
Solution found in 24 with accuracy 0.001
Solution is [ 0.19907474 -0.19708226  0.19507826]
Alpha = -4
Solution found in 118 with accuracy 0.001
Solution is [-0.98391535  0.98410245 -0.98428737]
Alpha = 5
Solution found in 25 with accuracy 0.001
Solution is [ 0.12175914 -0.1212829   0.12080389]
Alpha = -7
Solution found in 50 with accuracy 0.001
Solution is [-0.24236741  0.24253093 -0.24269201]
For w=1
Alpha = 2
Solution found in 5 with accuracy 0.001
Solution is [ 0.2002637  -0.19993771  0.19991392]
Alpha = -4
Solution found in 8 with accuracy 0.001
Solution is [-0.99972612  0.99981196 -0.9998703 ]
Alpha = 5
Solution found in 4 with accuracy 0.001
Solution is [ 0.1250697  -0.12507936  0.12499641]
Alpha = -7
Solution found in 4 with accuracy 0.001
Solution is [-0.24988462  0.25001157 -0.24997599]


# Problem 3

In [16]:
def CGM(b, A, x0, acc):
    
    x_old=x0
    r0 = b-np.dot(A, x_old)
    r_old=r0
    p_old=r0
    iter=0
    
    while True:
        print("Iteration %s" %iter)
        alpha_k=(np.dot(np.transpose(r_old), r_old))/(np.dot(np.transpose(p_old),np.dot(A, p_old)))
        x_new = x_old + np.dot(alpha_k, p_old)
        print("Conjugate gradient is p=%s" %p_old)
        r_new = r_old - alpha_k*np.dot(A, p_old)
        if (np.linalg.norm(r_new) < acc):
            print("Solution is %s" %x_new, "found in %s" %(iter+1), "iterations")
            break
        beta = (np.dot(np.transpose(r_new), r_new))/(np.dot(np.transpose(r_old), r_old))
        p_new = r_new + np.dot(beta, p_old)
        iter+=1
        x_old=x_new
        r_old=r_new
        p_old=p_new


## Task(a)

In [17]:
A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
b=np.array([1, 0, 1])
x0=np.array([0, 0, 0])
acc = 0.001
        
CGM(b, A, x0, acc)

Iteration 0
Conjugate gradient is p=[1 0 1]
Iteration 1
Conjugate gradient is p=[0.5 1.  0.5]
Solution is [1. 1. 1.] found in 2 iterations


## Task (b)

In [18]:
alpha=1
A = np.array([[alpha+1, -1, 1], [-1, alpha+1, -1], [1, -1, alpha+1]])
b=np.array([1, 0, 1])
x0=np.array([0, 0, 0])
acc = 0.001
        
CGM(b, A, x0, acc)

Iteration 0
Conjugate gradient is p=[1 0 1]
Iteration 1
Conjugate gradient is p=[0.22222222 0.66666667 0.22222222]
Solution is [0.5 0.5 0.5] found in 2 iterations


# Problem 4

In [19]:
np.random.seed=7

D = np.diag([1,2,3,4,5,6,7,8,9,10])

P = np.random.randint(1, 10, size=(10, 10))

A4 = np.dot(np.dot(P, D),np.linalg.inv(P))

## Task (a)

In [46]:
def power_eigen(A, x0, acc):
    x_old=x0
    iter=0
    alpha_k_old=0
    
    while True:
        alpha_k=np.absolute(x_old).max()
        x_new = np.dot(A, x_old)/alpha_k
        
        if np.linalg.norm(alpha_k-alpha_k_old) < acc:
            print("Solution found in %s" %iter, "iterations")
            print("Dominating eigenvalue is %.5f" %alpha_k)
            print("Dominating eigenvector is %s" %x_new)
            return alpha_k
            break
            
        alpha_k_old=alpha_k
        x_old=x_new
        iter+=1

In [47]:
np.random.seed=7
x0=np.random.randint(1, A4.shape[0], size=A4.shape[0])
acc=0.0001

power_eigen(A4, x0, acc)

print("Checking result...")
print("Maximal eigenvalue via built-in function is ", max(np.linalg.eig(A4)[0]))

print(np.linalg.eig(A4))

Solution found in 66 iterations
Dominating eigenvalue is 10.00086
Dominating eigenvector is [ -5.00269849  -2.49498882  -3.75173469  -8.75212019  -6.25134924
  -3.74710894 -10.00077096  -7.50462594  -6.25134919  -7.49653061]
Checking result...
Maximal eigenvalue via built-in function is  10.000000000000012
(array([ 1.,  2., 10.,  3.,  9.,  4.,  5.,  8.,  6.,  7.]), array([[ 0.15249857,  0.44232587, -0.24209101,  0.33145961,  0.07106691,
        -0.43915503, -0.0939682 , -0.38023455,  0.11268723,  0.54570516],
       [ 0.38124643,  0.24573659, -0.12104551,  0.37881098,  0.42640143,
        -0.29277002, -0.0939682 , -0.57035183,  0.22537447,  0.12126781],
       [ 0.30499714,  0.09829464, -0.18156826,  0.09470274,  0.07106691,
        -0.34156503, -0.0939682 , -0.06337243,  0.16903085,  0.06063391],
       [ 0.07624929,  0.19658927, -0.42365927,  0.37881098,  0.28426762,
        -0.39036003, -0.28190459, -0.19011728,  0.45074894,  0.30316953],
       [ 0.30499714,  0.44232587, -0.3026137

In [55]:
def power_method(A, x_0, max_iter_to, eps):
    i = 0
    while i < max_iter_to:
        x_1 = A@x_0
        lam = np.amax(np.abs(x_1))  
        x_1 = (1/lam)*x_1
        if np.linalg.norm(x_1-x_0) < eps:
            return lam, x_1  
        x_0 = x_1
        i = i+1
    print ('Power method did not converge')

In [57]:
np.random.seed=7
x0=np.random.randint(1, A4.shape[0], size=A4.shape[0])
acc=0.0001

a, b = power_method(A4, x0, 100, acc)

print(a)
print(b)

print("Checking result...")
print("Maximal eigenvalue via built-in function is ", max(np.linalg.eig(A4)[0]))

print(np.linalg.eig(A4))

10.000710579064343
[0.50021321 0.24952044 0.37513323 0.87513324 0.62507996 0.37470693
 1.         0.7503731  0.62507994 0.74962695]
Checking result...
Maximal eigenvalue via built-in function is  10.000000000000012
(array([ 1.,  2., 10.,  3.,  9.,  4.,  5.,  8.,  6.,  7.]), array([[ 0.15249857,  0.44232587, -0.24209101,  0.33145961,  0.07106691,
        -0.43915503, -0.0939682 , -0.38023455,  0.11268723,  0.54570516],
       [ 0.38124643,  0.24573659, -0.12104551,  0.37881098,  0.42640143,
        -0.29277002, -0.0939682 , -0.57035183,  0.22537447,  0.12126781],
       [ 0.30499714,  0.09829464, -0.18156826,  0.09470274,  0.07106691,
        -0.34156503, -0.0939682 , -0.06337243,  0.16903085,  0.06063391],
       [ 0.07624929,  0.19658927, -0.42365927,  0.37881098,  0.28426762,
        -0.39036003, -0.28190459, -0.19011728,  0.45074894,  0.30316953],
       [ 0.30499714,  0.44232587, -0.30261377,  0.42616235,  0.21320072,
        -0.29277002, -0.42285689, -0.2534897 ,  0.11268723,  0.2

## Task (b)

In [48]:
def inverse_power_eigen(A, mu, x0, acc):
    Amu = (A-mu*np.identity(A.shape[0]))
    A_inv = np.linalg.inv(Amu)
    
    lambd_mu = power_eigen(A_inv, x0, acc)
    
    lambd = (1 + mu*lambd_mu)/lambd_mu
    return lambd

In [54]:
np.random.seed=7
# mus = [4.8, 6.2, 7.5, 2.5]
mus = [7.1]
x0=np.random.randint(1, A4.shape[0], size=A4.shape[0])
acc=0.0001

for mu in mus:
    print("For inversed matrix:")
    res = inverse_power_eigen(A4, mu, x0, acc)
    print("Closes eigenvector aproximately equal to %.5f" %res)

For inversed matrix:
Solution found in 8 iterations
Dominating eigenvalue is 10.00000
Dominating eigenvector is [-10.00000018  -2.22222229  -1.11111113  -5.55555566  -4.44444453
  -6.6666668   -2.22222227  -8.88888906  -5.55555565  -4.44444452]
Closes eigenvector aproximately equal to 7.20000


# Problem 5

## Task (a)

In [24]:
np.random.seed=7

D = np.diag([1,2,3,4,5,6,7,8,9,10])

u=np.random.randint(1, D.shape[0], size=D.shape[0])

A5 = D + colvec(u)*u

In [34]:
def QR_eigens(A, acc):
    A_old=A
    iter=0
    EVcs=np.identity(A.shape[0])
    
    while True:
        Q, R = np.linalg.qr(A_old)
        A_new = np.dot(R, Q)
        if iter == 0:
            EVcs = Q
        else:
            EVcs = np.dot(EVcs, Q)
        
        if np.linalg.norm(A_new-A_old) < acc:
            print("Solution found in %s" %(iter+1), "iteration(s) with accuracy %s" %acc)
            print("Eigenvalues of matrix A are: \n %s" %np.diag(A_new).round(4))
            print("Eigenvectors are: \n %s" %EVcs.round(4))
            break
        
        A_old=A_new
        iter+=1

In [35]:
acc=0.0001

QR_eigens(A5, acc)

Solution found in 94 iteration(s) with accuracy 0.0001
Eigenvalues of matrix A are: 
 [345.9806   9.8569   8.4634   7.7021   6.6546   5.3773   4.9171   3.5881
   2.4532   1.0065]
Eigenvectors are: 
 [[ 0.0535  0.0038  0.0081  0.0088  0.0097 -0.0169 -0.0096 -0.017  -0.0273
  -0.9977]
 [ 0.4831  0.039   0.0838  0.0934  0.1065 -0.1976 -0.1162 -0.2487 -0.7875
   0.0589]
 [ 0.4307  0.0397  0.0882  0.1007  0.1205 -0.2495 -0.1571 -0.5969  0.5801
   0.0261]
 [ 0.378   0.0407  0.0944  0.1119  0.1452 -0.3768 -0.2872  0.7457  0.1794
   0.0152]
 [ 0.1083  0.014   0.0348  0.0438  0.0666 -0.3947  0.9055  0.0622  0.0311
   0.0033]
 [ 0.3259  0.053   0.1467  0.2087  0.5047  0.7148  0.2091  0.1092  0.0671
   0.0078]
 [ 0.2724  0.0596  0.2058  0.4216 -0.7973  0.2286  0.0905  0.0643  0.0436
   0.0054]
 [ 0.2185  0.0733  0.5193 -0.7955 -0.1637  0.1131  0.0489  0.0398  0.0286
   0.0037]
 [ 0.3836  0.2781 -0.7854 -0.3192 -0.1644  0.1433  0.0646  0.0568  0.0424
   0.0057]
 [ 0.2198 -0.9518 -0.1567 -0.103  -0

## Task (b)


In [40]:
np.random.seed=7
x0=np.random.randint(1, A5.shape[0], size=A5.shape[0])
acc=0.0001

power_eigen(A5, x0, acc)

print(np.linalg.eig(A5))

Solution found in 6 iterations
Dominating eigenvalue is 345.98064
Dominating eigenvector is [ 38.3308604  345.98064232 308.43501259 270.66980535  77.56102957
 233.36748971 195.04660725 156.49896102 274.68590852 157.43055612]
(array([345.98064231,   1.00651112,   9.85692304,   2.45317808,
         3.58808548,   8.46343656,   7.70214853,   6.65464773,
         5.37732832,   4.91709883]), array([[-0.05352647, -0.99773282, -0.00384397, -0.02728614, -0.01695496,
         0.00806546, -0.00883607,  0.00973848, -0.01695454,  0.00958778],
       [-0.4831387 ,  0.05885043, -0.03899895, -0.78747099, -0.24868176,
         0.08381991, -0.09347104,  0.10647617, -0.19777185,  0.11587079],
       [-0.43070875,  0.02607032, -0.03972131,  0.58010288, -0.59693196,
         0.0881439 , -0.10075503,  0.12054278, -0.24974458,  0.15672132],
       [-0.37797218,  0.01519115, -0.04069035,  0.17943976,  0.7457036 ,
         0.0944054 , -0.11197403,  0.14520711, -0.37718621,  0.28665828],
       [-0.10830876,  0