In [107]:
import numpy as np

from sympy import *

# Problem 1

## Task (c)

In [1]:
def LDU_matrixes(M):
    L = np.tril(M, -1)
    U = np.triu(M, 1)
    D = np.diag(np.diag(M))
    
    return L, D, U

In [70]:
def Jacobi_Iter_Single(Bj, dj, x_old):
    x_new = np.dot(Bj, x_old) + dj
    return x_new

def Jacobi_Iter (L, D, U, b, x0):
    Bj = np.dot(-np.linalg.inv(D), (L+U))
    dj = np.dot(np.linalg.inv(D), b)
    x_old = x0
    
    for i in range(0, 10):
        x_new = Jacobi_Iter_Single(Bj, dj, x_old)
        print(x_new)
        print(np.linalg.norm(x_new - x_old))
        x_old = x_new

In [71]:
A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
b=np.array([1, 0, 1])
x0=np.array([0, 0, 0])

L, D, U = LDU_matrixes(A)

Jacobi_Iter(L, D, U, b, x0)


[0.5 0.  0.5]
0.7071067811865476
[0.5 0.5 0.5]
0.5
[0.75 0.5  0.75]
0.3535533905932738
[0.75 0.75 0.75]
0.25
[0.875 0.75  0.875]
0.1767766952966369
[0.875 0.875 0.875]
0.125
[0.9375 0.875  0.9375]
0.08838834764831845
[0.9375 0.9375 0.9375]
0.0625
[0.96875 0.9375  0.96875]
0.04419417382415922
[0.96875 0.96875 0.96875]
0.03125


Jacobi decay rate equals to p(A)**k

## Task(d)

In [310]:
def GS_Iter_Single(Bgs, dgs, x_old):
    x_new = np.dot(Bgs, x_old) + dgs
    return x_new

def GS_Iter (L, D, U, b, x0):
    Bgs = np.dot(-np.linalg.inv(L+D), U)
    dgs = np.dot(np.linalg.inv(L+D), b)
    x_old = x0
    norms=[]
#     xs.append(x_old)
    
    for i in range(0, 10):
        x_new = GS_Iter_Single(Bgs, dgs, x_old)
#         print(x_new)
#         xs.append(x_new)
#         print(xs[i-2])
        norms.append(np.linalg.norm(x_new - x_old))
#         print(np.linalg.norm(x_new - x_old))
        print(norms[i]/norms[i-1])
        x_old = x_new
    
    print(norms)

In [311]:
A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
b=np.array([1, 0, 1])
x0=np.array([0, 0, 0])

L, D, U = LDU_matrixes(A)

GS_Iter(L, D, U, b, x0)

1.0
0.5217491947499509
0.6428571428571429
0.5
0.5
0.5
0.5
0.5
0.5
0.5
[0.8385254915624212, 0.4375, 0.28125, 0.140625, 0.0703125, 0.03515625, 0.017578125, 0.0087890625, 0.00439453125, 0.002197265625]


## Task (e)

In [312]:
def SOR_Iter_Single(Bsor, dsor, x_old):
    x_new = np.dot(Bsor, x_old) + dsor
    return x_new

def SOR_Iter (L, D, U, b, x0, w):
    Bsor = np.dot(np.linalg.inv(w*L+D), ((1-w)*D-w*U))
    dsor = w*np.dot(np.linalg.inv(w*L+D), b)
    x_old = x0
    
    for i in range(0, 10):
        x_new = SOR_Iter_Single(Bsor, dsor, x_old)
        print(x_new)
        print(np.linalg.norm(x_new - x_old))
        x_old = x_new

In [315]:
A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
b=np.array([1, 0, 1])
x0=np.array([0, 0, 0])
w=1.1

L, D, U = LDU_matrixes(A)

SOR_Iter(L, D, U, b, x0, w)

[0.55     0.3025   0.716375]
0.9524701520913924
[0.661375   0.7275125  0.87849438]
0.4683190232433876
[0.88399437 0.89661756 0.95529022]
0.2899198344124941
[0.95474022 0.96085499 0.98294122]
0.09947863800585222
[0.98299622 0.98518009 0.99355493]
0.03876548874894403
[0.99354943 0.99438939 0.99755867]
0.014567472303895528
[0.99755922 0.9978759  0.99907588]
0.005525949257535369
[0.99907582 0.99919585 0.99965013]
0.0020909569304179846
[0.99965013 0.99969556 0.99986754]
0.000791715843896457
[0.99986754 0.99988474 0.99994985]
0.00029972156950813696


# Problem 2

## Task (b)

In [119]:
A = Matrix([[0, -(a+1)**2, (a+1)**2], [0, -(a+1), (a+1)-(a+1)**2], [0, a, -2*a-1]])
A.eigenvals()

{-a*sqrt(-4*a - 3)/2 - 3*a/2 - 1: 1, a*sqrt(-4*a - 3)/2 - 3*a/2 - 1: 1, 0: 1}

## Task (c)

In [145]:
def colvec(rowvec):
    v = np.asarray(rowvec)
    return v.reshape(v.size,1)

In [267]:
def Jacobi_Alpha(x0, acc, alpha, u):
    x_old = x0
    iter = 0
    
    while True:
#         print('Iteration=', iter)
        x_new = (1/(alpha+1))*(np.dot((-colvec(u)*u+np.identity(3)), x_old) + u)
#         print('1=',(1/(alpha+1)))
#         print('2=', np.dot((colvec(u)*u+np.identity(3)), x_old))
#         print('3=', u)
#         print('4=', x_new)
#         print(np.linalg.norm(x_new - x_old))
        if (np.linalg.norm(x_new - x_old) < acc) and (iter > 0):
            print("Solution found in %s" %iter, "iterations with accuracy %.3f" %acc)
            print("Solution is %s" %x_new)
            break
        iter += 1
        x_old = x_new

In [274]:
u=np.array([1, -1, 1])
x0=np.array([0, 0, 0])
alphas = [2, -4, 5, -7]
acc = 0.001

for alpha in alphas:
    print("Alpha = %.0f" %alpha)
    Jacobi_Alpha(x0, acc, alpha, u)

Alpha = 2
Solution found in 16 iterations with accuracy 0.001
Solution is [ 0.20020299 -0.20020299  0.20020299]
Alpha = -4
Solution found in 16 iterations with accuracy 0.001
Solution is [-0.99898504  0.99898504 -0.99898504]
Alpha = 5
Solution found in 6 iterations with accuracy 0.001
Solution is [ 0.12505716 -0.12505716  0.12505716]
Alpha = -7
Solution found in 6 iterations with accuracy 0.001
Solution is [-0.24988569  0.24988569 -0.24988569]


## Task (d)


In [322]:
def GS_Alpha(x0, acc, alpha):
    x_old = x0
    iter = 0
    Bgs =  -1 * np.array([[0, -(alpha+1)**2, (alpha+1)**2], 
                                       [0, -(alpha+1), (alpha+1)-(alpha+1)**2], 
                                       [0, alpha, -2*alpha-1]])
    
    dgs=np.array([[(alpha+1)**2], [(alpha+1)-(alpha+1)**2], [-2*alpha-1+(alpha+1)**2]])
    
    while True:
        
        x_new = (1/(alpha+1)**3)*(np.dot(Bgs, colvec(x_old))+dgs)
#         print(np.dot(Bgs, colvec(x_old)))
#         print(x_new)
        if (np.linalg.norm(x_new - x_old) < acc) and (iter > 0):
            print("Solution found in %s" %iter, "with accuracy %.3f" %acc)
            print("Solution is %s" %x_new.T)
            break
        iter += 1
        x_old = x_new

In [323]:
x0=np.array([0, 0, 0])
alphas = [2, -4, 5, -7]
acc = 0.001

for alpha in alphas:
    print("Alpha = %.0f" %alpha)
    GS_Alpha(x0, acc, alpha)

Alpha = 2
Solution found in 4 with accuracy 0.001
Solution is [[ 0.1997895  -0.2000151   0.20006513]]
Alpha = -4
Solution found in 9 with accuracy 0.001
Solution is [[-0.99944338  0.99957274 -0.99967204]]
Alpha = 5
Solution found in 3 with accuracy 0.001
Solution is [[ 0.12498361 -0.12499756  0.12500314]]
Alpha = -7
Solution found in 4 with accuracy 0.001
Solution is [[-0.24997562  0.24998778 -0.2499939 ]]


## Task (e)

In [340]:
def SOR_Iter_Single(Bsor, dsor, x_old):
    x_new = np.dot(Bsor, x_old) + dsor
    return x_new

def SOR_Iter (L, D, U, b, x0, w):
    Bsor = np.dot(np.linalg.inv(w*L+D), ((1-w)*D-w*U))
    dsor = w*np.dot(np.linalg.inv(w*L+D), b)
    x_old = x0
    iter = 0
    
    while True:
        x_new = SOR_Iter_Single(Bsor, dsor, x_old)
#         print(x_new)
#         print(np.linalg.norm(x_new - x_old))
        if (np.linalg.norm(x_new - x_old) < acc) and (iter > 0):
            print("Solution found in %s" %iter, "with accuracy %.3f" %acc)
            print("Solution is %s" %x_new.T)
            break
        iter += 1
        x_old = x_new

In [341]:
b=np.array([1, -1, 1])
x0=np.array([0, 0, 0])
ws=[0.1, 1.1]
alphas = [2, -4, 5, -7]
acc = 0.001

for w in ws:
    print("For w=%.f" %w)
    for alpha in alphas:
        print("Alpha = %.0f" %alpha)
        A = np.array([[alpha+1, -1, 1], [-1, alpha+1, -1], [1, -1, alpha+1]])

        L, D, U = LDU_matrixes(A)

        SOR_Iter(L, D, U, b, x0, w)

For w=0
Alpha = 2
Solution found in 23 with accuracy 0.001
Solution is [ 0.19907474 -0.19708226  0.19507826]
Alpha = -4
Solution found in 117 with accuracy 0.001
Solution is [-0.98391535  0.98410245 -0.98428737]
Alpha = 5
Solution found in 24 with accuracy 0.001
Solution is [ 0.12175914 -0.1212829   0.12080389]
Alpha = -7
Solution found in 49 with accuracy 0.001
Solution is [-0.24236741  0.24253093 -0.24269201]
For w=1
Alpha = 2
Solution found in 4 with accuracy 0.001
Solution is [ 0.2002637  -0.19993771  0.19991392]
Alpha = -4
Solution found in 7 with accuracy 0.001
Solution is [-0.99972612  0.99981196 -0.9998703 ]
Alpha = 5
Solution found in 3 with accuracy 0.001
Solution is [ 0.1250697  -0.12507936  0.12499641]
Alpha = -7
Solution found in 3 with accuracy 0.001
Solution is [-0.24988462  0.25001157 -0.24997599]


# Problem 3

## Task(a)

In [249]:
def conjugate_product(a, b, A):
    return (np.dot(np.dot(a, A), b))

In [251]:
a = np.array([1,1,0])
b = np.array([0,0,-1])
A=np.array([[1,1,-1], [-1,1,1], [1,1,1]])

print(conjugate_product(a, b, A))

0


In [ ]:
A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
b=np.array([1, 0, 1])
x0=np.array([0, 0, 0])

x_old=x0

def CGM(b, A):
    r = b-np.dot(A, x_old)
    
    for i in len(b):
        p = r - 