In [2]:
import numpy as np

# Problem 1

## Task (c)

In [3]:
def LDU_matrixes(M):
    L = np.tril(M, -1)
    U = np.triu(M, 1)
    D = np.diag(np.diag(M))
    
    return L, D, U

In [4]:
def Jacobi_Iter_Single(Bj, dj, x_old):
    x_new = np.dot(Bj, x_old) + dj
    return x_new

def Jacobi_Iter (L, D, U, b, x0):
    Bj = np.dot(-np.linalg.inv(D), (L+U))
    dj = np.dot(np.linalg.inv(D), b)
    x_old = x0
    
    for i in range(0, 10):
        x_new = Jacobi_Iter_Single(Bj, dj, x_old)
        print(x_new)
        print(np.linalg.norm(x_new - x_old))
        x_old = x_new

In [5]:
A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
b=np.array([1, 0, 1])
x0=np.array([0, 0, 0])

L, D, U = LDU_matrixes(A)

Jacobi_Iter(L, D, U, b, x0)


[0.5 0.  0.5]
0.7071067811865476
[0.5 0.5 0.5]
0.5
[0.75 0.5  0.75]
0.3535533905932738
[0.75 0.75 0.75]
0.25
[0.875 0.75  0.875]
0.1767766952966369
[0.875 0.875 0.875]
0.125
[0.9375 0.875  0.9375]
0.08838834764831845
[0.9375 0.9375 0.9375]
0.0625
[0.96875 0.9375  0.96875]
0.04419417382415922
[0.96875 0.96875 0.96875]
0.03125


Jacobi decay rate equals to p(A)**k

## Task(d)

In [226]:
def GS_Iter_Single(Bgs, dgs, x_old):
    x_new = np.dot(Bgs, x_old) + dgs
    return x_new

def GS_Iter (L, D, U, b, x0):
    Bgs = np.dot(-np.linalg.inv(L+D), U)
    dgs = np.dot(np.linalg.inv(L+D), b)
    x_old = x0
    norms=[]
#     xs.append(x_old)
    
    for i in range(0, 10):
        x_new = GS_Iter_Single(Bgs, dgs, x_old)
#         print(x_new)
#         xs.append(x_new)
#         print(xs[i-2])
        norms.append(np.linalg.norm(x_new - x_old))
#         print(np.linalg.norm(x_new - x_old))
        print(norms[i]/norms[i-1])
        x_old = x_new
    
    print(norms)

In [227]:
A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
b=np.array([1, 0, 1])
x0=np.array([0, 0, 0])

L, D, U = LDU_matrixes(A)

GS_Iter(L, D, U, b, x0)

1.0
0.5217491947499509
0.6428571428571429
0.5
0.5
0.5
0.5
0.5
0.5
0.5
[0.8385254915624212, 0.4375, 0.28125, 0.140625, 0.0703125, 0.03515625, 0.017578125, 0.0087890625, 0.00439453125, 0.002197265625]


## Task (e)

In [8]:
def SOR_Iter_Single(Bsor, dsor, x_old):
    x_new = np.dot(Bsor, x_old) + dsor
    return x_new

def SOR_Iter (L, D, U, b, x0, w):
    Bsor = np.dot(np.linalg.inv(w*L+D), ((1-w)*D-w*U))
    dsor = w*np.dot(np.linalg.inv(w*L+D), b)
    x_old = x0
    
    for i in range(0, 10):
        x_new = SOR_Iter_Single(Bsor, dsor, x_old)
        print(x_new)
        print(np.linalg.norm(x_new - x_old))
        x_old = x_new

In [9]:
A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
b=np.array([1, 0, 1])
x0=np.array([0, 0, 0])
w=1.1

L, D, U = LDU_matrixes(A)

SOR_Iter(L, D, U, b, x0, w)

[0.55     0.3025   0.716375]
0.9524701520913924
[0.661375   0.7275125  0.87849438]
0.4683190232433876
[0.88399437 0.89661756 0.95529022]
0.2899198344124941
[0.95474022 0.96085499 0.98294122]
0.09947863800585222
[0.98299622 0.98518009 0.99355493]
0.03876548874894403
[0.99354943 0.99438939 0.99755867]
0.014567472303895528
[0.99755922 0.9978759  0.99907588]
0.005525949257535369
[0.99907582 0.99919585 0.99965013]
0.0020909569304179846
[0.99965013 0.99969556 0.99986754]
0.000791715843896457
[0.99986754 0.99988474 0.99994985]
0.00029972156950813696


# Problem 2

## Task (c)

In [10]:
def colvec(rowvec):
    v = np.asarray(rowvec)
    return v.reshape(v.size,1)

In [35]:
def Jacobi_Alpha(x0, acc, alpha, u):
    x_old = x0
    iter = 0
    
    while True:
#         print('Iteration=', iter)
        x_new = (1/(alpha+1))*(np.dot((-colvec(u)*u+np.identity(3)), x_old) + u)
#         print('1=',(1/(alpha+1)))
#         print('2=', np.dot((colvec(u)*u+np.identity(3)), x_old))
#         print('3=', u)
#         print('4=', x_new)
#         print(np.linalg.norm(x_new - x_old))
        if (np.linalg.norm(x_new - x_old) < acc) and (iter > 0):
            print("Solution found in %s" %(iter+1), "iterations with accuracy %.3f" %acc)
            print("Solution is %s" %x_new)
            break
        iter += 1
        x_old = x_new

In [36]:
u=np.array([1, -1, 1])
x0=np.array([0, 0, 0])
alphas = [2, -4, 5, -7]
acc = 0.001

for alpha in alphas:
    print("Alpha = %.0f" %alpha)
    Jacobi_Alpha(x0, acc, alpha, u)

Alpha = 2
Solution found in 17 iterations with accuracy 0.001
Solution is [ 0.20020299 -0.20020299  0.20020299]
Alpha = -4
Solution found in 17 iterations with accuracy 0.001
Solution is [-0.99898504  0.99898504 -0.99898504]
Alpha = 5
Solution found in 7 iterations with accuracy 0.001
Solution is [ 0.12505716 -0.12505716  0.12505716]
Alpha = -7
Solution found in 7 iterations with accuracy 0.001
Solution is [-0.24988569  0.24988569 -0.24988569]


## Task (d)


In [33]:
def GS_Alpha(x0, acc, alpha):
    x_old = x0
    iter = 0
    Bgs =  -1 * np.array([[0, -(alpha+1)**2, (alpha+1)**2], 
                                       [0, -(alpha+1), (alpha+1)-(alpha+1)**2], 
                                       [0, alpha, -2*alpha-1]])
    
    dgs=np.array([[(alpha+1)**2], [(alpha+1)-(alpha+1)**2], [-2*alpha-1+(alpha+1)**2]])
    
    while True:
        
        x_new = (1/(alpha+1)**3)*(np.dot(Bgs, colvec(x_old))+dgs)
#         print(np.dot(Bgs, colvec(x_old)))
#         print(x_new)
        if (np.linalg.norm(x_new - x_old) < acc) and (iter > 0):
            print("Solution found in %s" %(iter+1), "with accuracy %.3f" %acc)
            print("Solution is %s" %x_new.T)
            break
        iter += 1
        x_old = x_new

In [34]:
x0=np.array([0, 0, 0])
alphas = [2, -4, 5, -7]
acc = 0.001

for alpha in alphas:
    print("Alpha = %.0f" %alpha)
    GS_Alpha(x0, acc, alpha)

Alpha = 2
Solution found in 5 with accuracy 0.001
Solution is [[ 0.1997895  -0.2000151   0.20006513]]
Alpha = -4
Solution found in 10 with accuracy 0.001
Solution is [[-0.99944338  0.99957274 -0.99967204]]
Alpha = 5
Solution found in 4 with accuracy 0.001
Solution is [[ 0.12498361 -0.12499756  0.12500314]]
Alpha = -7
Solution found in 5 with accuracy 0.001
Solution is [[-0.24997562  0.24998778 -0.2499939 ]]


## Task (e)

In [31]:
def SOR_Iter_Single(Bsor, dsor, x_old):
    x_new = np.dot(Bsor, x_old) + dsor
    return x_new

def SOR_Iter (L, D, U, b, x0, w):
    Bsor = np.dot(np.linalg.inv(w*L+D), ((1-w)*D-w*U))
    dsor = w*np.dot(np.linalg.inv(w*L+D), b)
    x_old = x0
    iter = 0
    
    while True:
        x_new = SOR_Iter_Single(Bsor, dsor, x_old)
#         print(x_new)
#         print(np.linalg.norm(x_new - x_old))
        if (np.linalg.norm(x_new - x_old) < acc) and (iter > 0):
            print("Solution found in %s" %(iter+1), "with accuracy %.3f" %acc)
            print("Solution is %s" %x_new.T)
            break
        iter += 1
        x_old = x_new

In [32]:
b=np.array([1, -1, 1])
x0=np.array([0, 0, 0])
ws=[0.1, 1.1]
alphas = [2, -4, 5, -7]
acc = 0.001

for w in ws:
    print("For w=%.f" %w)
    for alpha in alphas:
        print("Alpha = %.0f" %alpha)
        A = np.array([[alpha+1, -1, 1], [-1, alpha+1, -1], [1, -1, alpha+1]])

        L, D, U = LDU_matrixes(A)

        SOR_Iter(L, D, U, b, x0, w)

For w=0
Alpha = 2
Solution found in 24 with accuracy 0.001
Solution is [ 0.19907474 -0.19708226  0.19507826]
Alpha = -4
Solution found in 118 with accuracy 0.001
Solution is [-0.98391535  0.98410245 -0.98428737]
Alpha = 5
Solution found in 25 with accuracy 0.001
Solution is [ 0.12175914 -0.1212829   0.12080389]
Alpha = -7
Solution found in 50 with accuracy 0.001
Solution is [-0.24236741  0.24253093 -0.24269201]
For w=1
Alpha = 2
Solution found in 5 with accuracy 0.001
Solution is [ 0.2002637  -0.19993771  0.19991392]
Alpha = -4
Solution found in 8 with accuracy 0.001
Solution is [-0.99972612  0.99981196 -0.9998703 ]
Alpha = 5
Solution found in 4 with accuracy 0.001
Solution is [ 0.1250697  -0.12507936  0.12499641]
Alpha = -7
Solution found in 4 with accuracy 0.001
Solution is [-0.24988462  0.25001157 -0.24997599]


# Problem 3

In [89]:
def CGM(b, A, x0, acc):
    
    x_old=x0
    r0 = b-np.dot(A, x_old)
    r_old=r0
    p_old=r0
    iter=0
    
    while True:
        print("Iteration %s" %iter)
        alpha_k=(np.dot(np.transpose(r_old), r_old))/(np.dot(np.transpose(p_old),np.dot(A, p_old)))
        x_new = x_old + np.dot(alpha_k, p_old)
        print("Conjugate gradient is p=%s" %p_old)
        r_new = r_old - alpha_k*np.dot(A, p_old)
        if (np.linalg.norm(r_new) < acc):
            print("Solution is %s" %x_new, "found in %s" %(iter+1), "iterations")
            break
        beta = (np.dot(np.transpose(r_new), r_new))/(np.dot(np.transpose(r_old), r_old))
        p_new = r_new + np.dot(beta, p_old)
        iter+=1
        x_old=x_new
        r_old=r_new
        p_old=p_new


## Task(a)

In [90]:
A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
b=np.array([1, 0, 1])
x0=np.array([0, 0, 0])
acc = 0.001
        
CGM(b, A, x0, acc)

Iteration 0
Conjugate gradient is p=[1 0 1]
Iteration 1
Conjugate gradient is p=[0.5 1.  0.5]
Solution is [1. 1. 1.] found in 2 iterations


## Task (b)

In [92]:
alpha=1
A = np.array([[alpha+1, -1, 1], [-1, alpha+1, -1], [1, -1, alpha+1]])
b=np.array([1, 0, 1])
x0=np.array([0, 0, 0])
acc = 0.001
        
CGM(b, A, x0, acc)

Iteration 0
Conjugate gradient is p=[1 0 1]
Iteration 1
Conjugate gradient is p=[0.22222222 0.66666667 0.22222222]
Solution is [0.5 0.5 0.5] found in 2 iterations


# Problem 4

In [148]:
np.random.seed=7

D = np.diag([1,2,3,4,5,6,7,8,9,10])

P = np.random.randint(1, 10, size=(10, 10))

A4 = np.dot(np.dot(P, D),np.linalg.inv(P))

## Task (a)

In [275]:
def power_eigen(A, x0, acc):
    x_old=x0
    iter=0
    alpha_k_old=0
    
    while True:
        alpha_k=np.absolute(x_old.max())
        x_new = np.dot(A, x_old)/alpha_k
        
        if np.linalg.norm(alpha_k-alpha_k_old) < acc:
            print("Solution found in %s" %iter, "iterations")
            print("Dominating eigenvalue is %.5f" %alpha_k)
            print("Dominating eigenvector is %s" %x_new)
            return alpha_k
            break
            
        alpha_k_old=alpha_k
        x_old=x_new
        iter+=1

In [264]:
np.random.seed=7
x0=np.random.randint(1, A4.shape[0], size=A4.shape[0])
acc=0.0001

power_eigen(A4, x0, acc)

print("Checking result...")
print("Maximal eigenvalue via built-in function is ", max(np.linalg.eig(A4)[0]))

Solution found in 64 iterations
Dominating eigenvalue is 9.99911
Dominating eigenvector is [3.75965906 6.26126801 7.50482992 7.49577414 5.00140797 6.2522142
 6.25402391 2.51066604 5.01227413 9.99919477]
Checking result...
Maximal eigenvalue via built-in function is  10.000000000000039


## Task (b)

In [260]:
def inverse_power_eigen(A, mu, x0, acc):
    Amu = (A-mu*np.identity(A.shape[0]))
    A_inv = np.linalg.inv(Amu)
    
    lambd_mu = power_eigen(A_inv, x0, acc)
    
    lambd = (1 + mu*lambd_mu)/lambd_mu
    return lambd

In [278]:
np.random.seed=7
# mus = [4.8, 6.2, 7.5, 2.5]
mus = [7.8]
x0=np.random.randint(1, A4.shape[0], size=A4.shape[0])
acc=0.0001

for mu in mus:
    print("For inversed matrix:")
    res = inverse_power_eigen(A4, mu, x0, acc)
    print("Closes eigenvector aproximately equal to %.5f" %res)

For inversed matrix:
Solution found in 12 iterations
Dominating eigenvalue is 5.00001
Dominating eigenvector is [-19.99999681  -9.99999853 -39.99999419 -24.99999627  -4.99999864
 -39.99999427  -9.99999811 -34.99999464  -4.99999914 -29.99999566]
Closes eigenvector aproximately equal to 8.00000


# Problem 5

## Task (a)

In [335]:
np.random.seed=7

D = np.diag([1,2,3,4,5,6,7,8,9,10])

u=np.random.randint(1, D.shape[0], size=D.shape[0])

A5 = D + colvec(u)*u

In [353]:
def QR_eigens(A, acc):
    A_old=A
    iter=0
    
    while True:
        Q, R = np.linalg.qr(A_old)
        A_new = np.dot(R, Q)
        
        if np.linalg.norm(A_new-A_old):
            print("Solution found in %s" %(iter+1), "iteration(s) with accuracy %s" %acc)
            print("Eigenvalues of matrix A are: \n %s" %np.diag(A_new).round(4))
            print("Eigenvectors are: \n %s" %Q.round(4))
            break
        
        A_old=A_new
        iter+=1

In [354]:
acc=0.0001

QR_eigens(A5, acc)

Solution found in 1 iteration(s) with accuracy 0.0001
Eigenvalues of matrix A are: 
 [315.902    1.6021   2.8957   3.5308   4.4003   5.9497   6.1686   7.911
   7.9688   9.6711]
Eigenvectors are: 
 [[-0.2402  0.6989  0.2224  0.3573  0.3227  0.0785  0.2779  0.0817  0.2543
  -0.1337]
 [-0.3956 -0.7043  0.1946  0.3126  0.2823  0.0687  0.2432  0.0715  0.2225
  -0.117 ]
 [-0.2261  0.0319 -0.9502  0.1191  0.1076  0.0262  0.0926  0.0272  0.0848
  -0.0446]
 [-0.4521  0.0637  0.0519 -0.8483  0.1613  0.0393  0.139   0.0409  0.1272
  -0.0669]
 [-0.4521  0.0637  0.0519  0.1255 -0.8634  0.0314  0.1112  0.0327  0.1017
  -0.0535]
 [-0.113   0.0159  0.013   0.0314  0.0361 -0.9916  0.0232  0.0068  0.0212
  -0.0111]
 [-0.3956  0.0558  0.0454  0.1098  0.1262  0.0356 -0.8964  0.0204  0.0636
  -0.0334]
 [-0.113   0.0159  0.013   0.0314  0.0361  0.0102  0.0397 -0.9912  0.0159
  -0.0084]
 [-0.3391  0.0478  0.039   0.0941  0.1082  0.0305  0.1191  0.0374 -0.9185
  -0.0223]
 [-0.1696  0.0239  0.0195  0.047   0.0

## Task (b)


In [355]:
np.random.seed=7
x0=np.random.randint(1, A5.shape[0], size=A5.shape[0])
acc=0.0001

power_eigen(A5, x0, acc)

Solution found in 6 iterations
Dominating eigenvalue is 316.00644
Dominating eigenvector is [155.9968699  273.86391381 156.99363451 314.99361771 316.00643796
  79.2564481  278.2952764   79.7710896  240.09277451 120.43868746]


316.0064387024271