In [150]:
import numpy as np
from fractions import Fraction

In [166]:
def qr_man(A: np.ndarray):
    
    ai = {}
    wi = {}
    
    W=np.empty_like(A, dtype=np.float32)
    D=np.zeros((len(A[0]),len(A[1])), dtype=np.float32)

    for i in range(len(A[1])):
        ai[i] = A.take(i, axis=1)
    
    for itm in ai:
        if itm==0:
            wi[itm]=ai[itm]
        elif itm==1:
            wi[itm]=ai[itm]-np.dot((np.dot(ai[itm].T, wi[itm-1]))/(np.dot(wi[itm-1].T, wi[itm-1])), wi[itm-1])
        elif itm==2:
            wi[itm]=ai[itm]-np.dot((np.dot(ai[itm].T, wi[itm-1]))/(np.dot(wi[itm-1].T, wi[itm-1])), wi[itm-1])-np.dot((np.dot(ai[itm].T, wi[itm-2]))/(np.dot(wi[itm-2].T, wi[itm-2])), wi[itm-2])
            
    for itm in wi:
        W[:,itm]=wi[itm]
    
    Wt=W.T

    for itm in wi:
        wi_len = np.sqrt(np.dot(wi[itm], wi[itm]))
        D[itm][itm] = wi_len
        
    Di=np.linalg.inv(D)
    
    R=np.dot(np.dot(Di,Wt),A)
    
    Q=np.dot(W,Di)
    
    return A, W, Wt, D, Di, R, Q;


## Problem 11
### (a)

In [193]:
B = np.array([[3, -1],
     [4, 3]])

A, W, Wt, D, Di, R, Q = qr_man(B)

print("A=", A)
print("W=", W.round(4))
print("Wt=", Wt.round(4))
print("D=", D.round(4))
print("Di=", Di.round(4))
print("R=", R.round(4))
print("Q=", Q.round(4))
print(np.allclose(A,np.dot(Q, R)))

A= [[ 3 -1]
 [ 4  3]]
W= [[ 3.   -2.08]
 [ 4.    1.56]]
Wt= [[ 3.    4.  ]
 [-2.08  1.56]]
D= [[5.  0. ]
 [0.  2.6]]
Di= [[0.2    0.    ]
 [0.     0.3846]]
R= [[ 5.   1.8]
 [-0.   2.6]]
Q= [[ 0.6 -0.8]
 [ 0.8  0.6]]
True


In [197]:
A = np.array([[3, -1],
     [4, 3]])

print("A = ",A)

Qa, Ra=np.linalg.qr(A)
print("Ra = ", Ra.round(4))
print("Qa = ", Qa.round(4))

print(np.allclose(A,np.dot(Qa, Ra)))

A =  [[ 3 -1]
 [ 4  3]]
Ra =  [[-5.  -1.8]
 [ 0.   2.6]]
Qa =  [[-0.6 -0.8]
 [-0.8  0.6]]
True


### (b)

In [194]:
B = np.array([[1, 2],
              [2, 1],
              [2, 4]])

A, W, Wt, D, Di, R, Q = qr_man(B)

print("A=", A)
print("W=", W.round(4))
print("Wt=", Wt.round(4))
print("D=", D.round(4))
print("Di=", Di.round(4))
print("R=", R.round(4))
print("Q=", Q.round(4))
print(np.allclose(A,np.dot(Q, R)))

A= [[1 2]
 [2 1]
 [2 4]]
W= [[ 1.      0.6667]
 [ 2.     -1.6667]
 [ 2.      1.3333]]
Wt= [[ 1.      2.      2.    ]
 [ 0.6667 -1.6667  1.3333]]
D= [[3.     0.    ]
 [0.     2.2361]]
Di= [[0.3333 0.    ]
 [0.     0.4472]]
R= [[3.     4.    ]
 [0.     2.2361]]
Q= [[ 0.3333  0.2981]
 [ 0.6667 -0.7454]
 [ 0.6667  0.5963]]
True


In [196]:
A = np.array([[1, 2],
              [2, 1],
              [2, 4]])

print("A = ", A)

Qa, Ra=np.linalg.qr(A)
print("Ra = ", Ra.round(4))
print("Qa = ", Qa.round(4))

print(np.allclose(A,np.dot(Qa, Ra)))

A =  [[1 2]
 [2 1]
 [2 4]]
Ra =  [[-3.     -4.    ]
 [ 0.      2.2361]]
Qa =  [[-0.3333  0.2981]
 [-0.6667 -0.7454]
 [-0.6667  0.5963]]
True


### (c)

In [198]:
B = np.array([[1, 2, 2],
              [2, -1, 1],
              [2, 0, 1]])

A, W, Wt, D, Di, R, Q = qr_man(B)

print("A=", A)
print("W=", W.round(4))
print("Wt=", Wt.round(4))
print("D=", D.round(4))
print("Di=", Di.round(4))
print("R=", R.round(4))
print("Q=", Q.round(4))
print(np.allclose(A,np.dot(Q, R)))

A= [[ 1  2  2]
 [ 2 -1  1]
 [ 2  0  1]]
W= [[ 1.      2.      0.1333]
 [ 2.     -1.      0.2667]
 [ 2.      0.     -0.3333]]
Wt= [[ 1.      2.      2.    ]
 [ 2.     -1.      0.    ]
 [ 0.1333  0.2667 -0.3333]]
D= [[3.     0.     0.    ]
 [0.     2.2361 0.    ]
 [0.     0.     0.4472]]
Di= [[0.3333 0.     0.    ]
 [0.     0.4472 0.    ]
 [0.     0.     2.2361]]
R= [[ 3.      0.      2.    ]
 [ 0.      2.2361  1.3416]
 [-0.      0.      0.4472]]
Q= [[ 0.3333  0.8944  0.2981]
 [ 0.6667 -0.4472  0.5963]
 [ 0.6667  0.     -0.7454]]
True


In [205]:
A = np.array([[1, 2, 2],
              [2, -1, 1],
              [2, 0, 1]])

print("A = ", A)

Qa, Ra=np.linalg.qr(A)
print("Ra = ", Ra.round(4))
print("Qa = ", Qa.round(4))

print(np.allclose(A,np.dot(Qa, Ra)))

A =  [[ 1  2  2]
 [ 2 -1  1]
 [ 2  0  1]]
Ra =  [[-3.      0.     -2.    ]
 [ 0.      2.2361  1.3416]
 [ 0.      0.     -0.4472]]
Qa =  [[-0.3333  0.8944 -0.2981]
 [-0.6667 -0.4472 -0.5963]
 [-0.6667 -0.      0.7454]]
True
