In [2]:
import numpy as np
from fractions import Fraction

In [3]:
from sympy import Matrix 



A = np.array([[1, 1, 1],
              [1, -1, 1]])
A = Matrix(A)
NA = A.nullspace()
print(NA)

[Matrix([
[-1],
[ 0],
[ 1]])]


## Problem 11

In [4]:
def qr_man(A: np.ndarray):
    
    ai = {}
    wi = {}
    
    W=np.empty_like(A, dtype=np.float32)
    D=np.zeros((len(A[0]),len(A[1])), dtype=np.float32)

    for i in range(len(A[1])):
        ai[i] = A.take(i, axis=1)
    
    for itm in ai:
        if itm==0:
            wi[itm]=ai[itm]
        elif itm==1:
            wi[itm]=ai[itm]-np.dot((np.dot(ai[itm].T, wi[itm-1]))/(np.dot(wi[itm-1].T, wi[itm-1])), wi[itm-1])
        elif itm==2:
            wi[itm]=ai[itm]-np.dot((np.dot(ai[itm].T, wi[itm-1]))/(np.dot(wi[itm-1].T, wi[itm-1])), wi[itm-1])-np.dot((np.dot(ai[itm].T, wi[itm-2]))/(np.dot(wi[itm-2].T, wi[itm-2])), wi[itm-2])
            
    for itm in wi:
        W[:,itm]=wi[itm]
    
    Wt=W.T

    for itm in wi:
        wi_len = np.sqrt(np.dot(wi[itm], wi[itm]))
        D[itm][itm] = wi_len
        
    Di=np.linalg.inv(D)
    
    R=np.dot(np.dot(Di,Wt),A)
    
    Q=np.dot(W,Di)
    
    return A, W, Wt, D, Di, R, Q;


### (a)

In [5]:
B = np.array([[3, -1],
     [4, 3]])

A, W, Wt, D, Di, R, Q = qr_man(B)

print("A=", A)
print("W=", W.round(4))
print("Wt=", Wt.round(4))
print("D=", D.round(4))
print("Di=", Di.round(4))
print("R=", R.round(4))
print("Q=", Q.round(4))
print(np.allclose(B,np.dot(Q, R)))

A= [[ 3 -1]
 [ 4  3]]
W= [[ 3.   -2.08]
 [ 4.    1.56]]
Wt= [[ 3.    4.  ]
 [-2.08  1.56]]
D= [[5.  0. ]
 [0.  2.6]]
Di= [[0.2    0.    ]
 [0.     0.3846]]
R= [[ 5.   1.8]
 [-0.   2.6]]
Q= [[ 0.6 -0.8]
 [ 0.8  0.6]]
True


In [6]:
A = np.array([[3, -1],
     [4, 3]])

print("A = ",A)

Qa, Ra=np.linalg.qr(A)
print("Ra = ", Ra.round(4))
print("Qa = ", Qa.round(4))

print(np.allclose(A,np.dot(Qa, Ra)))

A =  [[ 3 -1]
 [ 4  3]]
Ra =  [[-5.  -1.8]
 [ 0.   2.6]]
Qa =  [[-0.6 -0.8]
 [-0.8  0.6]]
True


### (b)

In [7]:
B = np.array([[1, 2],
              [2, 1],
              [2, 4]])

A, W, Wt, D, Di, R, Q = qr_man(B)

print("A=", A)
print("W=", W.round(4))
print("Wt=", Wt.round(4))
print("D=", D.round(4))
print("Di=", Di.round(4))
print("R=", R.round(4))
print("Q=", Q.round(4))
print(np.allclose(B,np.dot(Q, R)))

A= [[1 2]
 [2 1]
 [2 4]]
W= [[ 1.      0.6667]
 [ 2.     -1.6667]
 [ 2.      1.3333]]
Wt= [[ 1.      2.      2.    ]
 [ 0.6667 -1.6667  1.3333]]
D= [[3.     0.    ]
 [0.     2.2361]]
Di= [[0.3333 0.    ]
 [0.     0.4472]]
R= [[3.     4.    ]
 [0.     2.2361]]
Q= [[ 0.3333  0.2981]
 [ 0.6667 -0.7454]
 [ 0.6667  0.5963]]
True


In [8]:
A = np.array([[1, 2],
              [2, 1],
              [2, 4]])

print("A = ", A)

Qa, Ra=np.linalg.qr(A)
print("Ra = ", Ra.round(4))
print("Qa = ", Qa.round(4))

print(np.allclose(A,np.dot(Qa, Ra)))

A =  [[1 2]
 [2 1]
 [2 4]]
Ra =  [[-3.     -4.    ]
 [ 0.      2.2361]]
Qa =  [[-0.3333  0.2981]
 [-0.6667 -0.7454]
 [-0.6667  0.5963]]
True


### (c)

In [9]:
B = np.array([[1, 2, 2],
              [2, -1, 1],
              [2, 0, 1]])

A, W, Wt, D, Di, R, Q = qr_man(B)

print("A=", A)
print("W=", W.round(4))
print("Wt=", Wt.round(4))
print("D=", D.round(4))
print("Di=", Di.round(4))
print("R=", R.round(4))
print("Q=", Q.round(4))
print(np.allclose(B,np.dot(Q, R)))

A= [[ 1  2  2]
 [ 2 -1  1]
 [ 2  0  1]]
W= [[ 1.      2.      0.1333]
 [ 2.     -1.      0.2667]
 [ 2.      0.     -0.3333]]
Wt= [[ 1.      2.      2.    ]
 [ 2.     -1.      0.    ]
 [ 0.1333  0.2667 -0.3333]]
D= [[3.     0.     0.    ]
 [0.     2.2361 0.    ]
 [0.     0.     0.4472]]
Di= [[0.3333 0.     0.    ]
 [0.     0.4472 0.    ]
 [0.     0.     2.2361]]
R= [[ 3.      0.      2.    ]
 [ 0.      2.2361  1.3416]
 [-0.      0.      0.4472]]
Q= [[ 0.3333  0.8944  0.2981]
 [ 0.6667 -0.4472  0.5963]
 [ 0.6667  0.     -0.7454]]
True


In [10]:
A = np.array([[1, 2, 2],
              [2, -1, 1],
              [2, 0, 1]])

print("A = ", A)

Qa, Ra=np.linalg.qr(A)
print("Ra = ", Ra.round(4))
print("Qa = ", Qa.round(4))

print(np.allclose(A,np.dot(Qa, Ra)))

A =  [[ 1  2  2]
 [ 2 -1  1]
 [ 2  0  1]]
Ra =  [[-3.      0.     -2.    ]
 [ 0.      2.2361  1.3416]
 [ 0.      0.     -0.4472]]
Qa =  [[-0.3333  0.8944 -0.2981]
 [-0.6667 -0.4472 -0.5963]
 [-0.6667 -0.      0.7454]]
True


## Problem 12
### (c)

In [104]:
def colvec(rowvec):
    v = np.asarray(rowvec)
    return v.reshape(v.size,1)

In [250]:
def householder_qr(A: np.ndarray):
    
    Atmp = A
    Qdict={}
    i=0
    Q: np.ndarray
    
    while (Atmp.shape[0] > 1):
        print(Atmp.shape)
        In=np.identity(Atmp.shape[0])
        x = Atmp[:,0]
        xn = np.linalg.norm(Atmp[:,0], 2)
        ev = np.zeros_like(Atmp[:,0])
        ev[0]=xn
        u=x-ev
        un = u/np.linalg.norm(u, 2)
        H=In - 2 * colvec(un) * un.T
        print("iter=", x, xn, ev, u, In, H, un, Atmp)
    
        R=np.dot(H, Atmp)
        Qdict[i]=H
        i+1
        Atmp = np.dot(H, Atmp)
        Atmp = Atmp[1:,1:]
        print(Atmp)
    
    print(Qdict)
    for itm in Qdict:
        if itm == 0:
            Q=Qdict[itm]
        else:
            Q=np.dot(Q, Qdict[itm])
    
    return R, Q

In [251]:
B = np.array([[3, -1],
              [4, 3]])

R, Q = householder_qr(B)

print("R=", R.round(4))
print("Q=", Q.round(4))
print(np.allclose(B,np.dot(Q, R)))

(2, 2)
iter= [3 4] 5.0 [5 0] [-2  4] [[1. 0.]
 [0. 1.]] [[ 0.6  0.8]
 [ 0.8 -0.6]] [-0.4472136   0.89442719] [[ 3 -1]
 [ 4  3]]
[[-2.6]]
{0: array([[ 0.6,  0.8],
       [ 0.8, -0.6]])}
R= [[ 5.   1.8]
 [ 0.  -2.6]]
Q= [[ 0.6  0.8]
 [ 0.8 -0.6]]
True


In [252]:
B = np.array([[1, 2],
              [2, 1],
              [2, 4]])

R, Q = householder_qr(B)

print("R=", R.round(4))
print("Q=", Q.round(4))
# print(np.allclose(B,np.dot(Q, R)))

(3, 2)
iter= [1 2 2] 3.0 [3 0 0] [-2  2  2] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] [[ 0.33333333  0.66666667  0.66666667]
 [ 0.66666667  0.33333333 -0.66666667]
 [ 0.66666667 -0.66666667  0.33333333]] [-0.57735027  0.57735027  0.57735027] [[1 2]
 [2 1]
 [2 4]]
[[-1.]
 [ 2.]]
(2, 1)
iter= [-1.  2.] 2.2360679774997894 [2.23606798 0.        ] [-3.23606798  2.        ] [[1. 0.]
 [0. 1.]] [[-0.4472136   0.89442719]
 [ 0.89442719  0.4472136 ]] [-0.85065081  0.52573111] [[-1.]
 [ 2.]]
[]
{0: array([[-0.4472136 ,  0.89442719],
       [ 0.89442719,  0.4472136 ]])}
R= [[2.2361]
 [0.    ]]
Q= [[-0.4472  0.8944]
 [ 0.8944  0.4472]]
